### ISSUE TITLE
Frame rate non-constant

### ISSUE THREAD

**Issue by GabK** [dciets/Arcade-CS-Games#13]
J'en parlais avec @FalconX4 hier et on a réalisé que les jeux se basant sur pygame.time.get_ticks() (ou toute autre fonction de temps) réagissent différemment d.pendant de la machine sur lequel il roule.

La raison est qu'on a pas forcé de frame rate pour les minigames.

Je suis en processus de régler le problème mais va falloir que je fassent des légères modifications dans tous les jeux qui utilisent le temps! Je vous tiens au courrant. :)

**Comment by eucalyp** [comment]
Est-ce que tu va forcer un frame rate maintenant?

**Comment by becojo** [comment]
On pourrait pas juste avoir un `update` constant et un `render` indépendant? Le tout serait gérer dans le framework.

**Comment by GabK** [comment]
@anbuf : Ouais, je pensais forcer un frame rate de 30 fps; La méthode tick() de chaque minigame roulerait donc à chaque 33.33 ms

@Becojo : Ça marcherait aussi. Y'a un avantage de le faire comme ça? Je ne suis pas un expert en game dev alors je suis ouvert aux suggestions!

**Comment by AlexandreArpin** [comment]
@Becojo Bonne idée!

**Comment by eucalyp** [comment]
D'accord avec le update et render indépendant.

**Comment by GabK** [comment]
Je ne suis pas certain de comprendre ce que vous voulez dire par une méthode render et update indépendantes mais ce que j'ai commencé se trouve dans la branche `fixed-fps` (bc42b1f).

Vous pouvez regarder les classes `games_states/minigame.py` et `minigames/minigame.py` où j'ai défini les attributs `elapsed_ms` et `frame` qui compte respectivement les millisecondes et les frames écoulés depuis le début du minigame de manière constante.

**Comment by becojo** [comment]
En gros:
- Le rendu est effectué autant de fois que possible 
- L'update est effectué à intervalle fixe

Par contre, je réalise que c'est probablement trop compliqué pour ce qui est nécéssaire. Si l'ordinateur qui va exécuter le jeu peut faire le 30 FPS, le frame rate fixe est parfait.

À titre de référence, il y a une très bonne explication des différentes techniques pour résoudre ce problème dans le livre _Game Programming Patterns_: http://gameprogrammingpatterns.com/game-loop.html

**Comment by GabK** [comment]
Ah ouais, je comprends maintenant! De ce que je comprends, le Clock de pygame ne fixe pas le frame rate à une certaine valeur mais il empêche le jeu de rouler plus rapidement que la valeur passée en paramètre.

Je pense bien que la machine qui va exécuter les minigames peut faire du 30 fps sans problème. Étant donné qu'il nous reste pas trop trop de temps, je préfère garder ça simple en limitant le frame rate. :)

Je continue ça ce soir et je vous tiens au courrant!
