### ISSUE TITLE
Catch before the floor

### ISSUE THREAD

**Issue by eucalyp** [dciets/Arcade-CS-Games#5]
Je pensais également faire un jeu que vous avez probablement déjà tous jouer où l'on doit appuyer sur un bouton juste avant qu'un objet touche le sol. Si quelqu'un veut se lancer go for it.

**Comment by GabK** [comment]
Pour demeurer dans l'esprit des superstitions, le jeu pourrait être de descendre une échelle le plus bas possible sans tomber dans de la lave ou de quoi du genre!

http://imgur.com/w7e23Zv

**Comment by FalconX4** [comment]
J'avais oublier ce post mais j'ai fait de quoi du genre
https://github.com/dciets/Arcade-CS-Games-2015/tree/cutlery_fall

2015-02-25 23:36 GMT-05:00 Gabriel Kenderessy notifications@github.com:
