### ISSUE TITLE
Mécanisme de détection d'activité d'un joueur

### ISSUE THREAD

**Issue by GabK** [dciets/Arcade-CS-Games#9]
Peut-être que mon idée est trop complexe pour une simple arcade de dégrise, mais bon...
### Mise en situation

Samedi le 14 février 2015. 3h00 AM. Y'a du monde saoul un peu partout dans la salle de dégrise. L'arcade est libre et y'a deux gars (Player 1 et Player 2) qui décident de faire un match. Aucun problème jusqu'à présent.

Après 1 minigame de passé, Player 2 ne se sent pas bien et se sauve de l'arcade en vitesse. Problème: l'arcade ne sait pas qu'il y a un joueur de moins et y'a de fortes chances qu'il y aille une quantité considérable d'alcool de gaspillé!
### Solution 1

Player 1 met les 2 tuyaux dans sa bouche comme un champion et sort vainqueur à tous les niveaux
### Solution 2

On crée un mécanisme qui écoute les inputs de chaque joueur. Si un joueur n'a pas donner de input (Joystick ou bouton) après un certain temps, il est considéré comme "inactif" et la pompe ne fourni plus d'alcool à ce joueur.
### Considérations

Admettons qu'on veut implémenter la solution 2, il faudrait aussi implémenter le fait qu'un joueur pourrait jouer seul sur l'arcade.

Comme j'ai dit, c'est probablement trop de trouble, mais... l'idée est lancée!

**Comment by eucalyp** [comment]
1. J'aime l'idée se ne pas gaspiller d'alcool
2. Je sais pas à quel point le input c'est fiable, mais on a pas grand
   chose d'autres à part une potentielle camera
3. On manque probablement de temps pour le faire.

**Comment by jerome-gingras** [comment]
On avait déjà penser mettre un "weak button" sur l'arcade pour les gens qui veulent pas se defoncer ou les cas où quelqur part.
